'''
Comentario
en
varias
lineas
'''


numero = int(input("ingrese el numero 1 "))
numero2 = int(input("Ingrese el numero 2 "))

if numero > numero2 :
 suma = numero + numero2
 print ("El numero mayor es: ", numero, "La suma de los numeros: ", numero, numero2, "Es: ", suma)
else:
 resta = numero2 - numero
 print("El numero mayor es: ", numero2, "La resta de los numeros: ", numero, numero2, "Es: ", resta) 